name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 4"
  push:
    branches: 
      - main

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Env
        run: echo "TIMESTAMP=$(date +%y.%m.%d.%H.%M)" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build & push
        env:
          TAG_VERSION: ${{ github.run_number }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
          PLATFORM: linux/amd64,linux/arm/v7,linux/arm64
        run: |
          sudo apt update && sudo apt install curl &&
          ./image-build.sh